// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxmjrfuqp5GcKEErEL7_OdHc4wptiz46U',
    appId: '1:992168202992:web:467dbaeb5a26f56efda835',
    messagingSenderId: '992168202992',
    projectId: 'whatsapp-223e4',
    authDomain: 'whatsapp-223e4.firebaseapp.com',
    storageBucket: 'whatsapp-223e4.appspot.com',
    measurementId: 'G-PBKZR03KDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyxlDWzW8o-k2sJmXSPfu5hY6NNfkiFso',
    appId: '1:992168202992:android:1abbcdc1d80734f7fda835',
    messagingSenderId: '992168202992',
    projectId: 'whatsapp-223e4',
    storageBucket: 'whatsapp-223e4.appspot.com',
  );
}
